# Generated by Django 5.0.4 on 2024-04-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_remove_task_created_at_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
